### ISSUE TITLE
Todo list from feedback.

### ISSUE THREAD

**Issue by jpwsutton** [jpwsutton/node-red-node-grovepi#1]
- [ ] Look into PWM for output nodes, Input could be pain number so that analogue values could influence directly.
- [ ] Only enable output if receiving 1, "1", "on" or true. All other values should set to off to prevent accidents.
- [x] Analogue nodes should return a number, not a string. Also, clarify this in the help text.
- [x] Remove 'grove' from the name of the nodes, also use the blue colour from here: http://www.dexterindustries.com/grovepi/
- [ ] For simple digital inputs, send just 1 or 0 to make simple flows simple. I.e. could wire a button straight into a output node.
- [x] Include topic in messages to show where they came from. Something like grovepi/{sensortype}/{slot}
- [x] Labels on nodes should reflect the sensor type / pin. I.e. 'analogue - 1' or 'range - 2'. `return this.name||"analogue : "+this.pin;`
- [ ] Check Spellings!
